config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'records#index'
   resources :records
   get 'about' => 'static_pages#about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/record.rb
class Record < ApplicationRecord
	validates :title, :date, :amount, presence: true
	def self.balance
        where("amount>?",0).sum(:amount)
    end

    def self.debt
        where("amount<?",0).sum(:amount)
    end

    def self.total
        total= (self.balance + self.debt) 
        return total
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/records_controller.rb
class RecordsController < ApplicationController
	def index
		@records= Record.all
	 	@balance= Record.balance
		@debt= Record.debt
	 	@total= Record.total
	 end

	 def create
	@record= Record.create(record_params)
	if @record.valid?
		flash[:success] = "Your record has been created!"
		redirect_to root_path
 	else
		flash[:alert] = "sorry! there has been an error!"
		render :new
		end
	end

	def edit
		 @record = Record.find(params[:id])


	end
	def update
		@record = Record.find(params[:id])
		 @record.update(record_params)
		if @record.valid?
				redirect_to root_path
			else
				render :edit
    		end
	end

	def destroy
		@record=Record.find(params[:id])
		@record.destroy
		redirect_to root_path
	end

	 private

	def record_params
		params.require(:record).permit(:title, :date , :amount)
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
	def about
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/records_helper.rb
module RecordsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Accounting Management</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Lobster" rel="stylesheet">
  </head>

  <body>
  	<nav class="navbar navbar-default">
  <div class="container-fluid">
    <%= render 'shared/nav' %>
</nav>
<div class = "container">
    <div class = "row">
      <div class = "col-xs-12 col-md-6 col-md-offset-3">
        <%= render 'shared/flash_messages' %>
    <%= yield %>
  </body>
</html>

app/views/records/edit.html.erb
<h1> Update your record</h1>
<%= simple_form_for @record, method: :patch do |f| %>
<%= f.input :title %>
<%= f.input :date %>
<%= f.input :amount %>
<%= f.submit 'Submit', class: 'btn btn-primary' %>
<% end %>

app/views/records/index.html.erb
<div class="panel panel-primary">
<div class="panel-body",background:#F9EECF>

    <h3>Balance= <%= @balance %></h3>
    <h3>Debt= <%= @debt %></h3>
    <h3>Total= <%= @total %></h3>
</div>
</div>
<div class="col-md-12">
        <h1>Account Records</h1>
        <hr>
        <table class="table">
            <tr>
                <th>Title</th>
                <th>Date</th>
                <th>Amount</th>
                <th>Action</th>
            </tr>
   		 <% @records.each do|record| %>
           <tr>
              <td><%= record.title %></td>
              <td><%= record.date %></td>
              <td><%= record.amount %></td> 
              <td><%= link_to 'Delete', record_path(record), method: :delete, class: 'btn btn-sm btn-danger', data: {confirm: "Are you sure?"} %>
                      <%= link_to 'Update', edit_record_path(record), class: 'btn btn-sm btn-success' %>
              </td>
            </tr>
           <% end %>
        </table>
</div>

app/views/records/new.html.erb
<%= simple_form_for Record.new do |record| %>
    <%= record.input :title %>
    <%= record.input :date %>
    <%= record.input :amount %>
     <%= record.submit 'Add Record', class: 'btn btn-primary' %>
   
<% end %> 

app/views/shared/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <% if message_type == "notice" %>
    <p class="alert alert-info alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= notice %></p>
  <% elsif message_type == "alert" %>
    <p class="alert alert-danger alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= alert %></p>
  <% else %>
    <div class="alert alert-<%= message_type %> alert-dismissible text-center"><button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button><%= message %></div>
  <% end %>
<% end %>

app/views/shared/_nav.html.erb
<div class="navbar-header">
    <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Account management</a>
    
  </div>
    
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to 'Add record', new_record_path %></li>
      <li><%= link_to 'About', about_path %></li>
    </ul>
</div>

app/views/static_pages/about.html.erb
<h1>About Account Management</h1>
<p> You are looking into the simple accounting application that lets you to input your debt, loan and sum and displays the information to you when needed.</p>